### ISSUE TITLE
demo app crash

### ISSUE THREAD

**Issue by DevulderJeanPaul** [dagronf/DSFMaxLengthDisplayTextField#1]
dyld[11073]: Library not loaded: @rpath/VIViewInvalidating.framework/Versions/A/VIViewInvalidating
  Referenced from: /Users/devulderjean-paul/Library/Developer/Xcode/DerivedData/TextField_Demo-axqsehvudewmvxgkparmaodnoynm/Build/Products/Debug/TextField Demo.app/Contents/MacOS/TextField Demo
  Reason: tried: '/Users/devulderjean-paul/Library/Developer/Xcode/DerivedData/TextField_Demo-axqsehvudewmvxgkparmaodnoynm/Build/Products/Debug/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' (no such file), '/Users/devulderjean-paul/Library/Developer/Xcode/DerivedData/TextField_Demo-axqsehvudewmvxgkparmaodnoynm/Build/Products/Debug/PackageFrameworks/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' (code signature in <2738D0B8-F3B2-3B10-ADF8-13F0C2B04593> '/Users/devulderjean-paul/Library/Developer/Xcode/DerivedData/TextField_Demo-axqsehvudewmvxgkparmaodnoynm/Build/Products/Debug/PackageFrameworks/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/swift/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' (no such file), '/Users/devulderjean-paul/Library/Developer/Xcode/DerivedData/TextField_Demo-axqsehvudewmvxgkparmaodnoynm/Build/Products/Debug/TextField Demo.app/Contents/MacOS/../Frameworks/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' (code signature in <2738D0B8-F3B2-3B10-ADF8-13F0C2B04593> '/Users/devulderjean-paul/Library/Developer/Xcode/DerivedData/TextField_Demo-axqsehvudewmvxgkparmaodnoynm/Build/Products/Debug/TextField Demo.app/Contents/Frameworks/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/swift/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' (no such file), '/Users/devulderjean-paul/Library/Developer/Xcode/DerivedData/TextField_Demo-axqsehvudewmvxgkparmaodnoynm/Build/Products/Debug/TextField Demo.app/Contents/MacOS/../Frameworks/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' (code signature in <2738D0B8-F3B2-3B10-ADF8-13F0C2B04593> '/Users/devulderjean-paul/Library/Developer/Xcode/DerivedData/TextField_Demo-axqsehvudewmvxgkparmaodnoynm/Build/Products/Debug/TextField Demo.app/Contents/Frameworks/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' (no such file), '/System/Library/Frameworks/VIViewInvalidating.framework/Versions/A/VIViewInvalidating' (no such file)
(lldb) 

hi, demo app crash
monterey 12.4, Xcode 12.3
<img width="1352" alt="Capture d’écran 2022-06-24 à 22 23 25" src="https://user-images.githubusercontent.com/38420258/175662003-e07478a0-e388-4a78-9dbb-5fb00373ae25.png">

**Comment by DevulderJeanPaul** [comment]
hi,
i resolve the problem when I check the button "Disable Library Validation" on Hardened Runtime
thanks,

**Comment by dagronf** [comment]
Changed the linkage of VIViewInvalidating to static within the library. Updating to 0.2.0 should resolve the issue.

Thanks for letting me know!
